sudo: false
language: python
python:
  - "2.7"

env:
  - DB="POSTGRESQL"
  - DB="MYSQL"

services:
  - mysql
  - postgres

before_install:
  - pip install codecov

install:
  - python setup.py -q develop
  - pip install -q psycopg2 mysqlclient
  - pip install -q -r test-requirements.txt

before_script:
  - psql -c 'create database modoboa_test;' -U postgres
  - mysql -e "create database IF NOT EXISTS modoboa_test;" -uroot
  - mysql -e "CREATE USER 'modoboa'@'localhost' IDENTIFIED BY 'modoboa'" -uroot;
  - mysql -e "GRANT ALL PRIVILEGES ON * . * TO 'modoboa'@'localhost';" -uroot;

script:
  - python ./tests.py
  - cd test_project
  - coverage run --source ../modoboa manage.py test modoboa.core modoboa.lib modoboa.admin.tests modoboa.limits modoboa.relaydomains

after_success:
  - codecov

