language: python
python:
  - "2.7"

before_install:
  - pip install codecov
  
install:
  - python setup.py -q install
  - pip install -q psycopg2

before_script:
  - psql -c 'create database modoboa_test;' -U postgres

script: 
  - python ./tests.py
  - cd test_project
  - coverage run --source ../modoboa manage.py test modoboa.core modoboa.lib

after_success:
  - codecov
  